In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Mean:", arr.mean())

Array: [1 2 3 4 5]
Mean: 3.0


Creating arrays

In [9]:
# Create arrays different ways
a = np.array([1, 2, 3, 4, 5])
b = np.zeros((3, 3))
c = np.ones((2, 4))
d = np.arange(0, 20, 2)   # start, stop, step
e = np.linspace(0, 1, 5)  # 5 evenly spaced numbers between 0 and 1

print("a:", a)
print("b:\n", b)
print("c:\n", c)
print("d:", d)
print("e:", e)
print("Shape of b:", b.shape)
print("Data type of a:", a.dtype)

a: [1 2 3 4 5]
b:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
c:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
d: [ 0  2  4  6  8 10 12 14 16 18]
e: [0.   0.25 0.5  0.75 1.  ]
Shape of b: (3, 3)
Data type of a: int64


Picking out specific numbers (indexing & slicing)

In [10]:
arr = np.array([10, 20, 30, 40, 50, 60])

print("First 3:", arr[:3])
print("Last 3:", arr[-3:])
print("Every 2nd:", arr[::2])

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix:\n", matrix)
print("Row 1:", matrix[1])
print("Column 1:", matrix[:, 1])
print("Element at row 2, col 1:", matrix[2, 1])

First 3: [10 20 30]
Last 3: [40 50 60]
Every 2nd: [10 30 50]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row 1: [4 5 6]
Column 1: [2 5 8]
Element at row 2, col 1: 8


Reshaping arrays

In [11]:
nums = np.arange(1, 13)
print("Original:", nums)

reshaped = nums.reshape(3, 4)
print("Reshaped 3x4:\n", reshaped)

reshaped2 = nums.reshape(4, 3)
print("Reshaped 4x3:\n", reshaped2)

Original: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped 4x3:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Doing math on whole arrays at once (broadcasting)

In [12]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print("Add:", x + y)
print("Multiply:", x * y)
print("Add scalar:", x + 100)
print("Multiply scalar:", x * 2)

matrix = np.array([[1, 2], [3, 4]])
print("Matrix + 10:\n", matrix + 10)

Add: [11 22 33]
Multiply: [10 40 90]
Add scalar: [101 102 103]
Multiply scalar: [2 4 6]
Matrix + 10:
 [[11 12]
 [13 14]]


Basic statistics (summarizing a bunch of numbers)

In [13]:
data = np.array([23, 45, 12, 67, 34, 89, 21])

print("Sum:", data.sum())
print("Mean:", data.mean())
print("Max:", data.max())
print("Min:", data.min())
print("Standard deviation:", data.std())
print("Sorted:", np.sort(data))

Sum: 291
Mean: 41.57142857142857
Max: 89
Min: 12
Standard deviation: 25.65628379089972
Sorted: [12 21 23 34 45 67 89]


Create a NumPy array of the numbers 1–20. Reshape it into a 4×5 matrix. Print the shape, and extract the 3rd row and the 2nd column.

In [14]:
nums = np.arange(1, 21)
print("Original:", nums)
reshaped = nums.reshape(4, 5)
print("Reshaped 4*5:\n", reshaped)


Original: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Reshaped 4*5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


Create two 3×3 matrices, A and B, with any numbers you like.

In [ ]:
A = np.array(